#include "prefix/prefix.h"

#include "data-mov/mov.h"
#include "data-mov/xchg.h"
#include "data-mov/movext.h"
#include "data-mov/cltd.h"
#include "data-mov/leave.h"
#include "data-mov/pop.h"
#include "data-mov/push.h"



#include "control-instr/call.h"
#include "control-instr/je.h"
#include "control-instr/ret.h"
#include "control-instr/jmp.h"
#include "control-instr/jbe.h"
#include "control-instr/jle.h"
#include "control-instr/jg.h"
#include "control-instr/jne.h"
#include "control-instr/jl.h"

#include "arith/dec.h"
#include "arith/inc.h"
#include "arith/neg.h"
#include "arith/imul.h"
#include "arith/mul.h"
#include "arith/idiv.h"
#include "arith/div.h"
#include "arith/cmp.h"
#include "arith/sub.h"
#include "arith/add.h"
#include "arith/adc.h"

#include "logic/and.h"
#include "logic/or.h"
#include "logic/not.h"
#include "logic/xor.h"
#include "logic/sar.h"
#include "logic/shl.h"
#include "logic/shr.h"
#include "logic/shrd.h"
#include "logic/test.h"
#include "logic/setne.h"

#include "string/rep.h"

#include "misc/misc.h"

#include "special/special.h"
